modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="snookcraft"
version="1.0.3"
displayName="SnookCraft"
credits="Written and Compiled in MCreator"
displayURL="https://discord.gg/e7F884P3AE"
logoFile="logo.png"
authors="DaGooRoo"
description='''
SnookCraft! A custom mod made for use on TheSnookums' MC Server.
'''

[[dependencies.snookcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.snookcraft]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0]"
    ordering="NONE"
    side="BOTH"



