modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="snookcraft"
version="1.0.2"
displayName="SnookCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="DaGooRoo"
description='''
SnookCraft! A custom mod made for use on TheSnookums' MC Server.
'''

[[dependencies.snookcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




